# 基础镜像
FROM redis
# author
MAINTAINER data-analysis 

# 挂载目录
VOLUME /home/data-analysis /redis
# 创建目录
RUN mkdir -p /home/data-analysis /redis
# 指定路径
WORKDIR /home/data-analysis /redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/data-analysis /redis/redis.conf
