# 基础镜像
FROM nginx
# author
MAINTAINER data-analysis 

# 挂载目录
VOLUME /home/data-analysis/projects/data-analysis-ui
# 创建目录
RUN mkdir -p /home/data-analysis/projects/data-analysis-ui
# 指定路径
WORKDIR /home/data-analysis/projects/data-analysis-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/data-analysis/projects/data-analysis-ui
