version : '1.0'
services:
  dataAnalysis-nacos:
    container_name: dataAnalysis-nacos
    image: nacos/nacos-server
    build:
      context: ./nacos
    environment:
      - MODE=standalone
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "0.0.0.0:8848:8848"
      - "0.0.0.0:9848:9848"
      - "0.0.0.0:9849:9849"
  data-analysis-nginx:
    container_name: data-analysis-nginx
    image: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html/dist:/home/data-analysis/projects/data-analysis-ui
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - data-analysis-gateway
    links:
      - data-analysis-gateway
  data-analysis-gateway:
    container_name: data-analysis-gateway
    build:
      context: ./data-analysis/gateway
      dockerfile: dockerfile
    ports:
      - "8080:8080"
  data-analysis-auth:
    container_name: data-analysis-auth
    build:
      context: ./data-analysis/auth
      dockerfile: dockerfile
    ports:
      - "9200:9200"
  data-analysis-modules-system:
    container_name: data-analysis-modules-system
    build:
      context: ./data-analysis/modules/system
      dockerfile: dockerfile
    ports:
      - "9201:9201"
  data-analysis-modules-gen:
    container_name: data-analysis-modules-gen
    build:
      context: ./data-analysis/modules/gen
      dockerfile: dockerfile
    ports:
      - "9202:9202"
  data-analysis-modules-job:
    container_name: data-analysis-modules-job
    build:
      context: ./data-analysis/modules/job
      dockerfile: dockerfile
    ports:
      - "9203:9203"
  data-analysis-modules-file:
    container_name: data-analysis-modules-file
    build:
      context: ./data-analysis/modules/file
      dockerfile: dockerfile
    ports:
      - "9300:9300"
    volumes:
    - ./data-analysis/uploadPath:/home/data-analysis/uploadPath
  data-analysis-visual-monitor:
    container_name: data-analysis-visual-monitor
    build:
      context: ./data-analysis/visual/monitor
      dockerfile: dockerfile
    ports:
      - "9100:9100"
  data-analysis-modules-business:
    container_name: data-analysis-modules-business
    build:
      context: ./data-analysis/modules/business
      dockerfile: dockerfile
    ports:
      - "9205:9205"
