version : '1.0'
services:
  dataAnalysis-nacos:
    container_name: dataAnalysis-nacos
    image: nacos/nacos-server
    build:
      context: ./nacos
    environment:
      - MODE=standalone
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "0.0.0.0:8848:8848"
      - "0.0.0.0:9848:9848"
      - "0.0.0.0:9849:9849"
  dataAnalysis-nginx:
    container_name: dataAnalysis-nginx
    image: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html/dist:/home/dataAnalysis/projects/dataAnalysis-ui
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - dataAnalysis-gateway
    links:
      - dataAnalysis-gateway
  dataAnalysis-gateway:
    container_name: dataAnalysis-gateway
    build:
      context: ./dataAnalysis/gateway
      dockerfile: dockerfile
    ports:
      - "8080:8080"
  dataAnalysis-auth:
    container_name: dataAnalysis-auth
    build:
      context: ./dataAnalysis/auth
      dockerfile: dockerfile
    ports:
      - "9200:9200"
  dataAnalysis-modules-system:
    container_name: dataAnalysis-modules-system
    build:
      context: ./dataAnalysis/modules/system
      dockerfile: dockerfile
    ports:
      - "9201:9201"
  dataAnalysis-modules-gen:
    container_name: dataAnalysis-modules-gen
    build:
      context: ./dataAnalysis/modules/gen
      dockerfile: dockerfile
    ports:
      - "9202:9202"
  dataAnalysis-modules-job:
    container_name: dataAnalysis-modules-job
    build:
      context: ./dataAnalysis/modules/job
      dockerfile: dockerfile
    ports:
      - "9203:9203"
  dataAnalysis-modules-file:
    container_name: dataAnalysis-modules-file
    build:
      context: ./dataAnalysis/modules/file
      dockerfile: dockerfile
    ports:
      - "9300:9300"
    volumes:
    - ./dataAnalysis/uploadPath:/home/dataAnalysis/uploadPath
  dataAnalysis-visual-monitor:
    container_name: dataAnalysis-visual-monitor
    build:
      context: ./dataAnalysis/visual/monitor
      dockerfile: dockerfile
    ports:
      - "9100:9100"
