# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER data-analysis 

# 挂载目录
VOLUME /home/data-analysis 
# 创建目录
RUN mkdir -p /home/data-analysis 
# 指定路径
WORKDIR /home/data-analysis 
# 复制jar文件到路径
COPY ./jar/data-analysis -modules-job.jar /home/data-analysis /data-analysis -modules-job.jar
# 启动定时任务服务
ENTRYPOINT ["java","-jar","data-analysis -modules-job.jar"]
